# netlify.toml
[build]
  base = "."  # Root directory of the project
  publish = "public"  # Where to store the build output
  functions = "src/functions"  # Directory for serverless functions
  command = "gatsby build"  # Command to install and build

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-gatsby"
